spring.application.name=parcelamento-contrato
server.port=${SERVER_PORT:8082}

# Configuracoes padrao de conexao com o banco da aplicacao.
spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:5432/pagamento_servico}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:ftob2005}

# Configuracoes do JPA/Hibernate para persistencia.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Caminho do JSON OpenAPI gerado automaticamente.
springdoc.api-docs.path=/v3/api-docs
# Caminho da interface Swagger UI.
springdoc.swagger-ui.path=/swagger-ui.html
# Ordena os endpoints por metodo HTTP na interface.
springdoc.swagger-ui.operationsSorter=method
# Ordena as tags em ordem alfabetica.
springdoc.swagger-ui.tagsSorter=alpha
